### ISSUE TITLE
An error occurred in the running program

### ISSUE THREAD

**Issue by ww5171351** [aioz-ai/CVPRW21_GPS#1]
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 161, in main
    train(cfg)
  File "train.py", line 31, in train
    train_loader, val_loader, num_query, num_classes = make_data_loader(cfg)
  File "H:\Code in the paper\CVPRW21_GPS-main\data\build.py", line 23, in make_data_loader
    dataset = init_dataset(cfg.DATASETS.NAMES, root=cfg.DATASETS.ROOT_DIR)
  File "H:\Code in the paper\CVPRW21_GPS-main\data\datasets\__init__.py", line 23, in init_dataset
    return __factory[name](*args, **kwargs)
  File "H:\Code in the paper\CVPRW21_GPS-main\data\datasets\market1501.py", line 50, in __init__
    train = self._process_dir(self.train_dir, relabel=True)
  File "H:\Code in the paper\CVPRW21_GPS-main\data\datasets\market1501.py", line 91, in _process_dir
    mask_path = osp.join(self.mask_dir, self.mask_path[img_id])
KeyError: 'dataset\\market1501\\bounding_box_train\\0002_c1s1_000451_03'

Please give me some advice，mogul.

**Comment by mzx987654** [comment]
File "/home/mzx/下载/CVPRW21_GPS-main/data/build.py", line 23, in make_data_loader
    dataset = init_dataset(cfg.DATASETS.NAMES, root=cfg.DATASETS.ROOT_DIR)
  File "/home/mzx/下载/CVPRW21_GPS-main/data/datasets/__init__.py", line 23, in init_dataset
    return __factory[name](*args, **kwargs)
  File "/home/mzx/下载/CVPRW21_GPS-main/data/datasets/market1501.py", line 51, in __init__
    query = self._process_dir(self.query_dir, relabel=False)
  File "/home/mzx/下载/CVPRW21_GPS-main/data/datasets/market1501.py", line 91, in _process_dir
    mask_path = osp.join(self.mask_dir, self.mask_path[img_id])
KeyError: '1488_c6s3_094992_00.jpg'
这个问题老哥遇到过么？

**Comment by widedh** [comment]
hello, this is due to an error in the naming, there is an extra '.jpg' at the end of some images..

**Comment by Linawdjn** [comment]
windows和Linux获取路径有'\\'和\'区别，可能是这个原因
